### ISSUE TITLE
fog-aws not working with dynamoDB Local

### ISSUE THREAD

**Issue by iMagesh** [fog/fog-aws#118]
This what i see on the terminal when i try to create a table using dynamodb local

``` bash
2.1.5 :046 > dynamo.create_table("people",
2.1.5 :047 >       {HashKeyElement: {AttributeName: "username", AttributeType: "S"}},
2.1.5 :048 >       {ReadCapacityUnits: 5, WriteCapacityUnits: 5})
Excon::Errors::BadRequest: Expected(200) <=> Actual(400 Bad Request)
excon.error.response
  :body          => "{\"__type\":\"com.amazonaws.dynamodb.v20120810#InvalidAction\",\"Message\":\"DynamoDB Local does not support v1 API.\"}"
  :headers       => {
    "Content-Length"   => "111"
    "Content-Type"     => "application/x-amz-json-1.0"
    "Server"           => "Jetty(8.1.12.v20130726)"
    "x-amzn-RequestId" => "c8d74d2d-a3fa-4b01-abeb-2aacacc2ef49"
  }
  :local_address => "::1"
  :local_port    => 53801
  :reason_phrase => "Bad Request"
  :remote_ip     => "127.0.0.1"
  :status        => 400
  :status_line   => "HTTP/1.1 400 Bad Request\r\n"
```

Is there a work around for this? or am i missing something? Please let me know.

**Comment by geemus** [comment]
Not sure what it means by "v1 API". Maybe we need to use a more recent API version for create table?

**Comment by iMagesh** [comment]
@geemus I think we need to upgrade to v2 API

**Comment by geemus** [comment]
I thought all the API versions were date based, rather than numerical though? Thats what I meant about not understanding what "version 2" meant, vs like `v20120810` for instance. We could probably just start rolling forward those dates to more recent ones, but we'll want to try and see if there are other changes we need to make alongside that roll forward.
