### ISSUE TITLE
IAM roles.all should paginate

### ISSUE THREAD

**Issue by tmonk42** [fog/fog-aws#176]
As of 0.7.6, if you call iam.roles.all, and you have > 100 roles, Fog::AWS::IAM fails to use IsTruncated and Marker to request the next batch of roles.

I did some experimenting with this, and if I updated https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/iam/roles.rb#L13 to accept options, I could make a call like this:
iam_roles = iam.roles.all('MaxItems' => 1000)
and that would get all of my roles in one call.

Spent a couple hours poking at this and couldn't seem to find the right combo to get pagination working properly...

**Comment by geemus** [comment]
I think PagedCollection is intended to handle this: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/iam/paged_collection.rb

You might try converting roles to this (from Collection) and it may "just work", otherwise, perhaps @lanej may be able to advise, as he wrote the PagedCollection code originally.

**Comment by tmonk42** [comment]
A+ thanks!
