### ISSUE TITLE
Fog::Storage::AWS::File#save deprecation warning without alternative

### ISSUE THREAD

**Issue by mcfadden** [fog/fog-aws#226]
I'm trying to update the `storage_class` on items in S3. In the documentation the only way I've been able to find a way to do this is via the `save` method on a File object. Apart from being a terribly inefficient way to accomplish this, it throws a deprecation warning that isn't particularly helpful in this case:

`options param is deprecated, use acl= instead`

Since I'm not setting the ACL, this doesn't actually help me.

I guess that leaves be with a multi-part question:

1) Is there a better way to be updating the storage class on items?

2) Is the entire options param deprecated or is it really just the `acl` option that is deprecated?

**Comment by geemus** [comment]
1) Hey, looks like AWS recommends using the copy object request for this purpose (http://docs.aws.amazon.com/AmazonS3/latest/dev/ChgStoClsOfObj.html). So I think you could use the `copy(target_directory, target_key, options)` and just pass the current directory/key as well as the storage options as the 3rd argument.
2) I believe only acl is actually intended to be deprecated there and it was made overly broad on accident (I suspect we didn't realize there were other options that were used there, it should probably look just for the ACL key in the conditional, would happily accept a patch).

Hope that helps, I'm going to close since I think this should resolve, but let me know if you have further questions or concerns.

Thanks!
wes
