### ISSUE TITLE
Fog::Storage::AWS::Files#each always iterates over entire collection

### ISSUE THREAD

**Issue by kyletolle** [fog/fog-aws#232]
I'm using S3 to store files, and this my my first time trying fog-aws. To get a feel for how things work, I'm playing around with fog using pry. In my testing, I've created a few files in our S3 bucket that I want to delete.

There are many other files that already exist, so I select only the files I'm interested in deleting. I do something like this:

```
files_to_delete = bucket.files.select{ |f| f.key.match(/somepattern/) }
```

I check that I've gotten the the number of files that I'd expect:

```
files_to_delete.count
=> 3
```

Seems that we're good to go.

Now, I want to destroy each of the files, so I do this:

```
files_to_delete.each(&:destroy)
```

It's taking a surprising amount of time to delete three files, so I Ctrl-C the operation.

I find now that, instead of deleting the three files I'd `select`d above, the `each` is operating on _all_ the files in the bucket. Instead of destroying the three files I was interested in, it's been destroying **all** the files in the bucket.

This behavior certainly caught me off guard. Is it intentional?

I'd expect [`Fog::Storage::AWS::Files#each`](https://github.com/fog/fog-aws/blob/master/lib/fog/aws/models/storage/files.rb#L43-L57) to iterate over the subcollection I've narrowed down to, instead of iterating over all the files. Fortunately, I stopped it before all the files were deleted, but it's scary to find that I could have unintentionally wiped out all the files in this directory.

To make things even more confusing, some methods work on the subset, which makes it very difficult to find out that `each` behaves this way. For instance, `count` returns the correct number of items in the subset. `map` iterates over the subset as well.

I'm interested in whether there is a workaround, or the potential for a change here. I'd hate to have others accidentally perform an operation on a much larger set of files than they'd expect.

Thanks for all the hard work on this library!

**Comment by kyletolle** [comment]
I wanted to share one workaround I discovered.

Doing a `select` on the `Fog::Storage::AWS::Files` object returns another Files object. You can move from that Files object to an Array.

To do so, change the first line of code in my original post to:

```
files_to_delete = bucket.files.select{ |f| f.key.match(/somepattern/) }.map{ |f| f}
```

Now you're working with an array of `Fog::Storage::AWS::File` objects, and can iterate over them like you'd expect.

**Comment by geemus** [comment]
@kyletolle hey, sorry for the confusion. Each is weird there in an effort to make pagination more easy to integrate with for users, which unfortunately has the result you indicate. What you have done was definitely going to be my suggestion (though perhaps `to_a` instead of `map`, I'm actually not sure if `to_a` works, but given this sort of thing perhaps it ought to). Also, some argument might be made for select doing something slightly different here (and returning an Array), but as I mentioned the pagination handling makes things more complicated. Hope that helps explain. Is there more you would like to discuss or work toward here or are we good to close this out now? Thanks!

**Comment by kyletolle** [comment]
Thanks for your reply @geemus. Using `to_a` instead of the `map` did work as well.

The fact that each handles the pagination is really nice. There was just the surprise that calling each on a "selected" subset of files iterates over all the files. I wonder if there's a way to help make it more apparent to others, so they can avoid deleting many more files than they'd expect. Would this be a good candidate for a note in the code describing the behavior?

**Comment by geemus** [comment]
Yeah, some details in the code sounds great, thanks!

**Comment by jslag** [comment]
Just ran into the same confusion.

I think that having `count` return one value, and then have `each` return a different number of records, is surprising, and not in a good way.

Getting all the matching files in the bucket could be useful functionality, but it would be better if there was something in the method calls that made the different behavior clear. I'm having a hard time coming up with a great name -- maybe `magically_growing_each` or something? Or could `each` only fetch more records if given an argument, eg. `files.each(keep_getting_records: true)`?

**Comment by geemus** [comment]
Yeah, that makes since, I'm also not sure what exactly to call it/how to fit it in to make things nice. At least we have the to_a workaround (though it is obviously NOT easy to find out about).

**Comment by spodlecki** [comment]
So, this still exists and I found it extremely unexpected.... and unfortunately, rspec tests didn't catch this... In this specific case, `fog-aws` is an option, not a certainty. So it needs to work with `fog-google` and `fog-local`. We use `fog-local` for integration testing... which I suppose we could make a test API Key / Secret for our rspec tests and actually integrate with a live aws account and see that files are not being deleted... but that should never be required... pagination or not, this really feels like a bug -- at the very least, extremely unexpected and the logic of the code is "bad"

#### Given an example of this code:
```
files = bucket.files.select{ |f| f.key.match(/somepattern/) }
files.each(&:destroy)
```
You would expect that only the files in `/somepattern/` would be destroyed, instead of the entire bucket.... right? Things to be considered as a fix, with the latter being the best imho

a. be a large notation in the documentation
b. be able to be displayed in a mock environment
c. rethought and made to behave as one would expect

#### easy examples of why you'd expect the above,
```
# A collection of models, that only modifies the selected
Model.where(foo: :bar).each(&:destroy)

# An array, that only modifies the selected
arr = ['a', 'b', 'c', 10, 11, 12]
selection = arr.select {|x| x.is_a?(String) }
selection.each {|x| puts x } # => 'a', 'b', 'c' and does not include the ints in the array
```

#### Temporary solution (hopefully not _the_ solution...)
I can confirm that `#to_a` will give me the specific files, instead of destroying the entire bucket...

**Comment by geemus** [comment]
Another option might be to use each instead of select initially, something like:

```
bucket.files.each { |f| f.key.match(/somepattern/) && f.destroy }
```

If I recall correctly the current behavior stems from an effort to accommodate buckets with enormous amounts of keys (as it deals with them one page at a time), vs select/to_a which would have to load them all in to memory.

I agree that, at the very least, we should improve the documentation around this as it is confusing and has been a gotcha. I'd be open to improving mocks and/or overall behavior, but I'm not certain how to accommodate the combination of a desire to not load everything in to memory and also to allow select usage like this (they seem directly at odds). `to_a` is a way to opt-in to the all-in-memory approach, if it works for a particular use case, but it is certainly not intuitive at all...

Perhaps our efforts here to make each "just work" for large buckets was too clever altogether, and it should have been the behavior that one could opt-in to instead. I'm somewhat reticent to make that (as it seems like it might break existing users in a different way), but it is certainly something we could consider as a future breaking change.

Thanks for you detailed report and understanding, I'm sorry that you ran into this.

**Comment by Aqualon** [comment]
I also just ran into this, it's really unexpected behavior.
