### ISSUE TITLE
Support Autoscaling lifecycle hooks

### ISSUE THREAD

**Issue by benmullin333** [fog/fog-aws#289]
Please consider supporting the following endpoints:
- http://docs.aws.amazon.com/cli/latest/reference/autoscaling/complete-lifecycle-action.html
- http://docs.aws.amazon.com/cli/latest/reference/autoscaling/delete-lifecycle-hook.html
- http://docs.aws.amazon.com/cli/latest/reference/autoscaling/describe-lifecycle-hook-types.html
- http://docs.aws.amazon.com/cli/latest/reference/autoscaling/describe-lifecycle-hooks.html
- http://docs.aws.amazon.com/cli/latest/reference/autoscaling/put-lifecycle-hook.html
- http://docs.aws.amazon.com/cli/latest/reference/autoscaling/record-lifecycle-action-heartbeat.html

**Comment by geemus** [comment]
Most new functionality gets added by somebody who needs it. This helps with motivation, but also tends to ensure it actually does what it needs to. Is there any chance you might be willing to help us out with these? We can certainly discuss and support the effort, but otherwise it may be a while before someone gets to it. Thanks!
