### ISSUE TITLE
Better contributing documentation

### ISSUE THREAD

**Issue by alepore** [fog/fog-aws#311]
Hello!

I think the contributing documentation can be improved, some things are not very clear for me:
- how to run a single test file?
- should i also run tests with real AWS credentials? how? or is the suite only for mocked tests?

Thanks :)

**Comment by geemus** [comment]
You can run an individual test with `bundle exec shindont path/to/test`.

We usually run the suite in mocked (because it is free and to avoid conflicting with existing resources on an account). You could certainly run them live, but I would advise doing it on a distinct space to avoid test failures and/or inadvertently changing things on an existing account (I believe you could do this by creating appropriately scoped IAM creds off an existing account). I think you can just do `FOG_MOCK=false` to have it run live tests, at which point it will try to pull credentials from `~/.fog`.

Hope that helps, thanks!
