### ISSUE TITLE
Why default VPC does not require Elastic IP to connect in internet

### ISSUE THREAD

**Issue by rajasekaran07** [fog/fog-aws#338]
Hello,

I have one small query in default VPC. Why default VPC does not require Elastic IP to connect in internet. As per VPC concept even through we are running our instance in VPC public subnet without attaching elaticIP or ELB we can't connect that in internet then how it is working in default VPC.

Regards,
Raja

**Comment by geemus** [comment]
@lanej do you have more direct experience with VPC? I haven't used it personally, so I'm pretty fuzzy on the specifics. Thanks!

**Comment by sbuzonas** [comment]
An internet gateway is required to have traffic flow between your instance and the internet. The default VPC has an IGW already, and it also has a route to `0.0.0.0/0` configured to pass through the IGW on the default subnet.

Using an ELB or EIP can give you access because of how they connect to your ENI, but that isn't the intent of either of those services. In a non-default VPC you should set up either an internet gateway or customer gateway (VPN) to direct your traffic to the internet. Additionally, you may require a NAT instance or NAT gateway that has access to an IGW in order to provide internet access to private subnets.

**Comment by geemus** [comment]
@sbuzonas thanks for the insight.

@rajasekaran07 hopefully that answers your question, but do follow up if we missed anything.
