### ISSUE TITLE
Not all Rds versions and Instance Types are rendered

### ISSUE THREAD

**Issue by chanakyad-cuelogic** [fog/fog-aws#371]
ref: `fog/aws/requests/rds/describe_orderable_db_instance_options.rb`
- When compared to AWS Console many versions were found missing 
For Eg:-
Scenario considered for Demonstration  
 - region:- 'ap-south-1'
 - engine:- 'postgres'
1. Through API 
- `c.describe_orderable_db_instance_options('postgres').data[:body]["DescribeOrderableDBInstanceOptionsResult"]["OrderableDBInstanceOptions"]`
=> Uniq versions were found ["9.4.7", "9.4.9", "9.4.11"]
2. When on AWS console and AWS API Reference (DescribeOrderableDBInstanceOptions)
 refer screenshot attached 
![screen shot 2017-06-20 at 8 32 14 pm](https://user-images.githubusercontent.com/8611339/27340415-04ad8636-55f8-11e7-8462-e2e2a74efa87.png)

**Comment by geemus** [comment]
We may need to bump the version of RDS we are using to get all the options? Otherwise I'm not sure why there would be such discrepancies.

**Comment by chanakyad-cuelogic** [comment]
@geemus 
will look at the version of rds to get all the options, i hope that would assist me to solve this 
Thanks 👍

**Comment by carloslima** [comment]
@chanakyad-cuelogic

You don't see all options because of the limit (100 maximum), if there are more than that amount of items (which is the case for that request[1]), it is required to make another request to fetch the next batch, until you reach the end.

You can get all options with:
```
require 'fog/aws'
options=Fog::AWS::RDS.new(region: 'ap-south-1').instance_options(engine: 'postgres')
all_options = options.to_a
all_options.concat(options.to_a) while options.filters[:marker] and options.all

puts all_options.map(&:engine_version).uniq
puts all_options.size

# 9.4.7
# 9.4.9
# 9.4.11
# 9.4.12
# 9.5.2
# 9.5.4
# 9.5.6
# 9.5.7
# 9.6.1
# 9.6.2
# 9.6.3
# 462
```

[1]: Just for clarity, each version is returned multiple times for each combination of instance size and options.

@geemus

In the code, Fog::AWS::RDS::InstanceOptions is a PagedCollection and it's implementation of #all has a comment stating that it intentionally only fetches the first page.

This makes me confused because considering there are other cases of paged collections, I would expect a standard way of:
1. knowing you got truncated results
2. a way to request the next page
3. a way to request all pages

I couldn't find such an option, so I thought of sending a PR for that but I wanted to ask for if such options already exist and if not if this would be a desired contribution.

**Comment by geemus** [comment]
I think the expectation around PagedCollection, if I recall correctly, is that if you want it all you use `each` instead of all. And that it should go through everything inside the block you pass, by loading/processing one page at a time. Does that make sense? Documentation could certainly be improved there, and I could imagine #next/#prev or something making sense. I'm certainly open to discussing further.

**Comment by carloslima** [comment]
Yes, you recall it correctly. I did manage to get the above example working with `each` but I intentionally didn't post it because I find it to be confusing as an example.
For instance:

```
carlos@rr-carlos ~/c/fog-aws (update-rds-instance-options-model)> cat b.rb
require 'fog/aws'
puts "### each"
options=Fog::AWS::RDS.new(region: 'ap-south-1').instance_options(engine: 'postgres')
options.each{|x| print 'x' }

puts "### size+each"
options=Fog::AWS::RDS.new(region: 'ap-south-1').instance_options(engine: 'postgres')
puts "size: #{options.size.to_s}"
i=0
options.each{|x| i+=1; print 'x' }
puts "\ntotal: #{i}"

puts "### all.each"
options=Fog::AWS::RDS.new(region: 'ap-south-1').instance_options(engine: 'postgres')
i=0
options.all.each{|x| i+=1; print 'x' }
puts "\ntotal: #{i}"


puts "### all.size+each"
options=Fog::AWS::RDS.new(region: 'ap-south-1').instance_options(engine: 'postgres')
puts "size: #{options.all.size}"
i=0
options.all.each{|x| i+=1; print 'x' }
puts "\ntotal: #{i}"


carlos@rr-carlos ~/c/fog-aws (update-rds-instance-options-model)> bundle exec pry b.rb
### each
### size+each
size: 100
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
total: 362
### all.each
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
total: 362
### all.size+each
size: 100
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
total: 262
carlos@rr-carlos ~/c/fog-aws (update-rds-instance-options-model)>
```

The problem, I think, is that it is a bit misleading.
In the documentation it is called a collection and it is an Enumerable but its has different semantics than what I would expect from standard ruby collections.
For instance, I find it confusing that:

* calling `.each` gives you no result
* calling `.all` gives you partial results (with no indication)
* calling `.all` multiple times gives you different results each time
* calling `.all.each` causes it to iterate not only the results from `.all` but to go over all pages (entries I didn't expect to be there)
* calling `.all.each` causes multiple api requests to happen (magically/hidden)

I'm not sure what the best solution here would be but just to throw in something for discussion, what about making each pagedcollection behave like a regular collection with the following additions:

`#last_page?`
true/false

`#first_page?` (needed?)
true/false

`#next_page`
returns another paged collection for the next page

`#prev_page` (needed?)
returns another paged collection for the previous page

`#all`
returns all items from the current page

`#each`
iterates over each items from the current page

`#all_pages`
load results from all pages and return a regular (non-paged) collection

What do you think?

**Comment by geemus** [comment]
Something like that sounds pretty reasonable to make this more explicit. The idea with each was to avoid the (potentially huge) data from all needing to be in memory at once and also to make it respond a bit faster when it actually takes multiple requests to build. That said, it is far from transparent. As you suggest, probably not all of those are needed here, but some of them could be helpful. I'll note though that we probably shouldn't change all/each behavior, as it would likely break things for someone (regardless of how weird it might seem). Does that make sense?

**Comment by carloslima** [comment]
You're absolutely right about not changing the current behavior. What would you suggest apart from the documentation?

Where is the documentation for the project? If I wanted to help make this clear, where should it go?

**Comment by geemus** [comment]
Perhaps adding some new methods, which are backwards compatible, but also provide better visibility would be a next step? What do you think?

Shared docs are a mix of inline in the code in relevant places and https://github.com/fog/fog.github.com (which is where fog.io is generated from), though the website hasn't seen much updates in a really long time.
