### ISSUE TITLE
 Regression: IO stream sent to AWS fails

### ISSUE THREAD

**Issue by giddie** [fog/fog-aws#388]
We have a backup script that creates a unix pipeline (tar & gpg), and streams the output through fog straight up to AWS S3 without an intermediate file. This works OK with fog 1.24.0:

```ruby
s3 = Fog::Storage::AWS.new({
  aws_access_key_id: 'ACCESS_KEY',
  aws_secret_access_key: 'SECRET_KEY',
  region: 'eu-west-1'
})
bucket = s3.directories.get('my-bucket')

IO.pipe do |data_out, data_in|
  data_in.write('hello')
  data_in.close
  bucket.files.create(
    key: 'my-file',
    body: data_out,
    multipart_chunk_size: 67108864
  )
end
```

This produces an "illegal seek" exception, caused by an attempt to rewind the stream (cf fog/fog issue #3246). However, in fog 1.24.0, this can be worked around be defining an empty method on the IO object's singleton class:

```ruby
def data_out.rewind
end
```

However, in fog master, this no longer works. Actually, a zero-length file is uploaded. Here's what I have so far:

1) I figured out that the file size is now zero because of some error-handling code in `excon` that retries the upload following an error. I disabled this in `/lib/fog/aws/storage.rb:596`, by adding the line:

```ruby
params[:idempotent] = (body.pos && true)  rescue false
```
2) The real error now presents itself:

```xml
<Error>
  <Code>IncompleteBody</Code>
  <Message>You did not provide the number of bytes specified by the Content-Length HTTP header</Message>
  <NumberBytesExpected>0</NumberBytesExpected>
  <NumberBytesProvided>5</NumberBytesProvided>
</Error>
```

This appears to be related to the `x-amz-decoded-content-length` header around `lib/fog/aws/storage.rb:582`. As described in [the linked AWS documentation](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html):

> When transferring data in a series of chunks, you must use the Content-Length HTTP header to explicitly specify the total content length (object length in bytes plus metadata in each chunk). This will require you to pre-compute the total length of the payload including the metadata you will send in each chunk before starting your request. The `x-amz-decoded-content-length` header will contain the size of the object length in bytes.

This clearly poses a problem for chunked uploads of streams, where the final file size is unknown up-front.

My question is this: fog 1.24.0 still uploads our stream OK. Does that mean that this signed header format is optional? Is it something we can switch off when the input data is a stream? Or is that an old API that Amazon will deprecate in the foreseeable future?

**Comment by geemus** [comment]
The docs indicate that `x-amz-decoded-content-length` is a required argument for v4 signatures, so I suspect that 1.24.0 (which is pretty old at this point) must be the earlier signature method.

> When transferring data in a series of chunks, you must use the Content-Length HTTP header to explicitly specify the total content length (object length in bytes plus metadata in each chunk). This will require you to pre-compute the total length of the payload including the metadata you will send in each chunk before starting your request. The x-amz-decoded-content-length header will contain the size of the object length in bytes.

As to deprecation, AWS docs indicate:

> Amazon S3 supports Signature Version 4, a protocol for authenticating inbound API requests to AWS services, in all AWS regions. At this time, AWS regions created before January 30, 2014 will continue to support the previous protocol, Signature Version 2. Any new regions after January 30, 2014 will support only Signature Version 4 and therefore all requests to those regions must be made with Signature Version 4. For more information about AWS Signature Version 2, see Signing and Authenticating REST Requests in the Amazon Simple Storage Service Developer Guide.

So, it might continue to work in old regions for now, but it might not be good to rely too strongly on that. You might be able to hack v2 signatures back into fog-aws (we kind of dropped them, because v4 worked everywhere and we hadn't run into any issues like this yet), but it might be better to provide the size if there is any possibility of that.

Sorry I'm not able to be more directly helpful, it seems AWS made their expectations more strict. It's certainly possible there are other workarounds, but I think they will be more general AWS level things rather than fog changes per se. Does that make sense? I'm happy to discuss further, but don't know how to workaround it at present. Maybe AWS forums/support or stack overflow can provide some more options for you?

**Comment by geemus** [comment]
Yeah. It's certainly possible there is some workaround on their side too, unfortunately I don't know of one from the docs though.
