### ISSUE TITLE
Spot instance creation : Support for BlockDurationMinutes

### ISSUE THREAD

**Issue by ruby2001** [fog/fog-aws#461]
Hi Team ,

AWS has the option to reserve/block spot instance for specific duration of time (https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RequestSpotInstances.html) .

Going through https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/compute/request_spot_instances.rb , the support to block spot instance for a specific duration seems to be not yet present in fog-aws . Is there any plan to add support for the same ? . It's really would be beneficial have this feature .

Thanks in advance ..

**Comment by geemus** [comment]
Generally we get things added as demand/interest allows. If you are interested, I would be happy to support a PR from you to add this feature. Otherwise, it likely would wait for someone else with particular interest in this feature to add it. Does that make sense? Would you be interested in contributing? Thanks!
