### ISSUE TITLE
Warning that doesn't make sense

### ISSUE THREAD

**Issue by WaKeMaTTa** [fog/fog-aws#479]
What is the meaning of this [warning](https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/storage/put_bucket.rb#L66) ?

> [WARNING] Your region 'eu-west-1' does not match the default region 'us-east-1'

Doesn't make any sense to me :confused:

**Comment by dgilperez** [comment]
Agreed. 

In our setup we need to configure `eu-west-1` for regulatory reasons and keep this warning coming up, telling us about something we already know ... is there a way we can silence it?

**Comment by geemus** [comment]
@WaKeMaTTa by default, fog will us the us-east-1 region (the original region) for storage requests. If your files are actually stored in another region, requesting them from us-east-1 will redirect the request to the region where the file is actually stored. Fog should automatically follow the redirect, so it will technically work, but this results in an extra request (the original request, plus the redirected request). Due to this, it is usually desirable to configure your connection to point directly at the region where your files exist in order to skip the extra requests. Does that make sense?

@dgilperez Yes, but it is currently an all-or-nothing for silencing warnings. By silencing this one you may end up missing other ones, just so you know. To silence, you can do this:

```
Fog::Logger[:warning] = nil
```
