### ISSUE TITLE
S3 Select Support?

### ISSUE THREAD

**Issue by eric-hemasystems** [fog/fog-aws#484]
Does fog have support for S3 Select? Here is the equivalent functionality I am referring to in the AWS SDK:

https://aws.amazon.com/blogs/developer/introducing-support-for-amazon-s3-select-in-the-aws-sdk-for-ruby/

I didn't see anything in the API or existing issues so I assume not but wanted to confirm.

**Comment by geemus** [comment]
Not that I know of. We usually work with interested parties to add features on-demand, rather than adding everything as it comes out. I don't recall anyone asking about this previously, so I just don't think we had gotten to it yet. I'd certainly support work on it if you or someone else wanted to take a crack at it. Thanks!
