### ISSUE TITLE
How to upload File to S3 with with accelerate?

### ISSUE THREAD

**Issue by luckymaniac** [fog/fog-aws#554]
I am using presigned_url with accelerate, but I got 400 on uploading.
```
storage = Fog::Storage.new(
      provider: 'AWS',
      region: 'accelerate',
      aws_access_key_id: ENV['AWS_ACCESS_KEY'],
      aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
    )

    options = { path_style: false }
    headers = { 'Content-Type' =>'image/jpeg', 'x-amz-acl' => 'public-read' }

    storage.put_object_url(
      ENV['AWS_S3_BUCKET_VIDEO'],
      'sample.jpg',
      15.minutes.from_now.to_time.to_i,
      headers,
      options
    )
```
Without `accelerate`, it's working perfectly.

Did I miss something?

I really appreciate if someone helps me out.

Thanks.

**Comment by geemus** [comment]
From a quick look at the code in: https://github.com/fog/fog-aws/blob/063c3f95308994947407c81ca19ca4fff219b742/lib/fog/aws/storage.rb. It looks like it expects the accelerate/acceleration parameter slightly differently. I think you can set the region normally, but then in the options you would want to add `acceleration: true` (which will change the host). I'm not exactly sure why it works that way (I didn't write it and haven't used it personally).

Additionally, have you been able to use acceleration on this bucket in any other way? It has to be enabled first, so that might be another possibility. Probably a good idea to double check the requirements here to make sure you have done them: https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html#transfer-acceleration-requirements

Hope that helps, without having used it myself it's a bit hard to know for sure. Certainly happy to discuss further and try to help as best I can though. If these things still don't fix it, the contents of the error might be helpful to pin it down further.

**Comment by luckymaniac** [comment]
> From a quick look at the code in: https://github.com/fog/fog-aws/blob/063c3f95308994947407c81ca19ca4fff219b742/lib/fog/aws/storage.rb. It looks like it expects the accelerate/acceleration parameter slightly differently. I think you can set the region normally, but then in the options you would want to add `acceleration: true` (which will change the host). I'm not exactly sure why it works that way (I didn't write it and haven't used it personally).
> 
> Additionally, have you been able to use acceleration on this bucket in any other way? It has to be enabled first, so that might be another possibility. Probably a good idea to double check the requirements here to make sure you have done them: https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html#transfer-acceleration-requirements
> 
> Hope that helps, without having used it myself it's a bit hard to know for sure. Certainly happy to discuss further and try to help as best I can though. If these things still don't fix it, the contents of the error might be helpful to pin it down further.

Thanks for your reply, @geemus 
But it didn't work, it didn't generate `acceleration` url, but just normal aws presigned_url.
With `region: 'accelerate'` the url is generated, but PUT operation is failing..
Thanks anyway

**Comment by geemus** [comment]
Does the error itself have any more context about what is making it a bad request?

**Comment by luckymaniac** [comment]
> Does the error itself have any more context about what is making it a bad request?

No.

**Comment by geemus** [comment]
Hmm. Yeah, the only other thing that comes to mind would be verifying that the bucket has acceleration turned on, which can probably be done in the web console (or by some other requests).

**Comment by luckymaniac** [comment]
I verified it double times, and bucket has acceleration on.

**Comment by geemus** [comment]
Thanks for checking. We may need to reach out to AWS and see if they can give us more information or suggestions, as it doesn't seem like we have enough information to easily figure out what else to try. Does that make sense?
