### ISSUE TITLE
Enable hibernation on creation of ec2 instance

### ISSUE THREAD

**Issue by taniahagan** [fog/fog-aws#566]
Hi fog-aws, 

Is it possible at all to enable hibernation on the creation of the ec2 instance?  I have enabled Ebs.Encryption successfully and believe I have all the prerequisites, but when adding the option:

args[:hibernation_options] = { 'Configured' => true } 

to /usr/share/foreman/app/models/compute_resources/foreman/model/ec2.rb I can see the parameter is passed in the logs but the vm is still not enabled for hibernation. 

Any pointers in the right direction would be much appreciated. 

Many thanks, 
Tania

**Comment by geemus** [comment]
I don't see any mention in our codebase, so it may be that we haven't implemented it yet. That being said, the code you callout appears to be in a different library, fwiw. I suspect it would be a relatively straightforward change to add support. Would you be interested in working on that?

**Comment by taniahagan** [comment]
If you could point us to the library I'd need to look at, I'm willing to give it a shot.  It would be a very useful feature to have.

**Comment by geemus** [comment]
I believe the change would need to happen in https://github.com/fog/fog-aws/blob/master/lib/fog/aws/requests/compute/run_instances.rb. Looking closely, maybe it would not need a change (though perhaps we would want some to make things work more easily/smoothly).

I think the option one needs to pass might be: `HibernationOptions.configured => true`. You should be able to try that and see if it gets you what you want. If it does, we might consider adding some helper functions to make it easier to set this (since this option doesn't look like the other ones that get passed in). In particular we might want to update the model to make it easier to set hibernation (more similar to what you originally tried) and have it get translated into the right invocation.

Does that make sense?

**Comment by taniahagan** [comment]
That does make sense, thank you.  I shall take a closer look.

**Comment by geemus** [comment]
Sounds good, happy to try and help if you have other questions along the way too.

**Comment by taniahagan** [comment]
I have submitted a pull request for review, and have successfully enabled hibernation and set instances for hibernation in my test environment.  https://github.com/fog/fog-aws/pull/569

**Comment by geemus** [comment]
Awesome, thanks. I just reviewed it.

**Comment by geemus** [comment]
Closing as related PR was merged.
