### ISSUE TITLE
max_keys param in storage.directories.get.... what am I missing?

### ISSUE THREAD

**Issue by ChrisPetr0** [fog/fog-aws#568]
Good day,

I'm new to using this library and potentially may want to use it to reset some object storage classes.  I'm playing around with it and I'm slightly confused.  

I'm initializing storage client like so:
```
s3 = Fog::AWS::Storage.new(aws_access_key_id: 'TRUNCATED', aws_secret_access_key: 'TRUNCATED', path_style: true)
```

Then I run a call on directories.get like so with `max_keys` and `prefix` options:
```
dir = s3.directories.get('target-bucket', {max_keys: 100000, prefix: ''})
```

I then see this in my interpreter:
```
pry(main)> dir.files.length
=> 1000
pry(main)> dir.files.all.length
=> 1000
pry(main)> dir.files.is_truncated
=> true
pry(main)> dir.files.all.is_truncated
=> true
```

Am I missing something with `max_keys` param?

Thanks,

Chris

**Comment by geemus** [comment]
It's been a little while since I've worked on this particular area, but if I recall correctly that is a limit imposed by AWS in the S3 service (you can only get 1000 per request, max keys is for restricting it to less than that, rather than asking for more).

Because of this we implemented `each` as a way to automatically deal with the multiple requests one "page" at a time if you need to touch every file. It would look something like:
```
dir.files.each do |file|
  puts file.inspect
end
```
Except you would replace the puts with probably something more useful. Hopefully that might help get you what you need (even though it would still only show 1000 at a time. Alternatively, you can make additional calls to get the next "page" like this:
```
page = dir.files
next_page = dir.files(marker: page.last.key)
```
Hope that helps.

**Comment by ChrisPetr0** [comment]
Thank you for the reply, I did review the source code some but it's definitely a lot to consume and understand in short amount of time :) .  

Anyhow, that makes sense, and yes AWS still limits paging to 1000.  I was taking max keys as enabling paging past 1000.

I'll play around a bit more and what you have said is helpful.  

Thanks again,

Chris

**Comment by geemus** [comment]
No worries, it's definitely a lot to take in. Just let me know if you have other questions.
