### ISSUE TITLE
Lambda IAM Role Not Working

### ISSUE THREAD

**Issue by metaskills** [fog/fog-aws#650]
Noticed today that an IAM Role is not working via the `:use_iam_profile` config as expected in AWS Lambda runtime. I found this worked:

```ruby
    config.fog_credentials      = {
      provider:        "AWS",
      region: ENV['AWS_REGION'],
      aws_access_key_id: ENV['AWS_SECRET_ACCESS_KEY'], 
      aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'], 
      aws_session_token: ENV['AWS_SESSION_TOKEN'], 
    }
```

Perhaps the `CredentialFetcher` should have something like this before the fall thru else condition? 

```ruby
elsif ENV['AWS_EXECUTION_ENV'] =~ /Lambda/
  ...
```

**Comment by geemus** [comment]
@metaskills Thanks for the heads up. Yeah, I hadn't thought about that case. I'd certainly be open to a patch to improve the behavior on Lambda if you are up for it. Might be good to talk through the specifics a bit more to make sure we are on the same page before going too deep though. What do you think?

**Comment by metaskills** [comment]
I might have time later on. I've not dug deep into how AWS SDKs handle this, but my assumption is they always yield to these environment variables when present. Tho I could be wrong. I could also be wrong on my assumption that these crews via the env are short term and guaranteed for the life of the function which could be up to 15m or so depending. Either way, I'd have to do a bit more research to make a PR. Thoughts?

**Comment by geemus** [comment]
@metaskills Yeah, I'm also not sure about which environment variables should get precedence (and when). I'd agree that digging into the AWS SDK would be a good place to look into in order to help us figure out what good options might be. So overall I'm in a similar spot to you in terms of feeling like we could probably do better, but not being sure exactly how best to do that. Some research as a next step when you find some time sounds great. Just let me know if you want to talk through it some more. Thanks!
