### ISSUE TITLE
URI.decode is obsolete (and not available in Ruby 3.0)

### ISSUE THREAD

**Issue by kuahyeow** [fog/fog-aws#653]
See https://ruby-doc.org/stdlib-2.5.3/libdoc/uri/rdoc/URI/Escape.html#method-i-unescape

It seems there's 4 usages still - https://github.com/fog/fog-aws/search?q=URI.decode

**Comment by geemus** [comment]
Thanks for the heads up. One possibility might be to use the solution we used for this in Excon, or something similar. As I recall there are quite a few caveats and potential edge cases in whatever solution one might choose though.

Here is the excon solution: https://github.com/excon/excon/blob/58a8d9511908c9cd8aa7e3649106eb7e3740cc8e/lib/excon/utils.rb#L103

Do you think something like that would be sufficient for our purposes? And/or do you have ideas of alternatives?

**Comment by geemus** [comment]
Sorry for the lack of context. Excon is an http library that fog uses for it's api calls, and that was originally embedded in fog before being extracted as it's own thing. So, under the covers fog is using it for a lot of this stuff and I've worked on both a lot, which is why that example came to mind.

I can't presently recall why we did it directly in Excon instead of using `URI.decode_www_form_component`. I think in an effort to maintain broader backwards compatibility.

All that said, I think you are probably right that in this case we could keep things simple and address the issue by using that method. Would you be up for making a pull request with that fix for us? Thanks!

**Comment by kuahyeow** [comment]
Oh I see, it looks like https://github.com/excon/excon/issues/334. so `decode_www_form_component` appears to be available since Ruby 1.9, and this gem supports Ruby >= 2.0.0 so we should be OK.

Sure,  I will make a pull request.

**Comment by kuahyeow** [comment]
I have opened https://github.com/fog/fog-aws/pull/654 now

**Comment by geemus** [comment]
@kuahyeow Good find, it somehow didn't occur to me to search back through the PRs to find that. Definitely makes sense that it would be an old version issue and also that it should be ok here as fog is more restrictive on versions than excon is/was. Thanks for checking in to that and refreshing my memory. I'll look at the PR presently.
